### ISSUE TITLE
Protocol unit tests require reference to every cmd entry

### ISSUE THREAD

**Issue by microbuilder** [microbuilder/LPC11U_LPC13U_CodeBase#13]
Minor issue, but the current unit test code requires every command tester references every other tester, which becomes cumbersome as the system grows.  Need to find a solution for this (single header listing every cmd?).

**Comment by hathach** [comment]
Fixed at f661e49dcd282a766c8d4149abcb8414ce27f797 use attribute weak in test build to resolve not-found command function to NULL instead of throwing errors.
