### ISSUE TITLE
undefined reference to 'spi_DL_slave_state_machine'

### ISSUE THREAD

**Issue by tummychow** [microbuilder/LPC11U_LPC13U_CodeBase#15]
I had a fresh clone of the repository (literally no changes) and I was on the development branch. Running make all results in the following:

```
src/core/ssp0_slave/ssp0_slave.c: In function 'SSP0_IRQHandler':
src/core/ssp0_slave/ssp0_slave.c:81:5: warning: implicit declaration of function 'spi_DL_slave_state_machine' [-Wimplicit-function-declaration]
     LPC_SSP0->DR = spi_DL_slave_state_machine(LPC_SSP0->DR);
     ^

bin/obj/ssp0_slave.o: In function `SSP0_IRQHandler':
/home/sjung/arm-alarm/src/core/ssp0_slave/ssp0_slave.c:81: undefined reference to `spi_DL_slave_state_machine'
collect2: error: ld returned 1 exit status
Makefile:422: recipe for target 'firmware' failed
make: *** [firmware] Error 1
```

I got the feeling that I was making a stupid mistake, but from a naive inspection, I don't see spi_datalayer.h included in ssp0_slave.c. I couldn't find it in the makefile either, so I added it:

```
VPATH += src/core/spi_datalayer
OBJS += $(OBJ_PATH)/spi_datalayer.o
```

right in between the entries for src/core/pmu and src/core/ssp0. (Following alphabetical order.) Running make all after this resolved the problem.

(One other thing: I had to run make lpcrc in tools/lpcrc after that. I figured out pretty quickly what to do and that the linux executable wasn't there, idk if there should be a mention of that though)

**Comment by tummychow** [comment]
correction to that little note at the end: I didn't read the makefile very well, haha. The lpcrc target was right there.

**Comment by tummychow** [comment]
Oh and, for completeness, here is the stderr log from `make all` after adding those two lines to the makefile:

```
src/core/spi_datalayer/spi_datalayer.c: In function 'spi_DL_master_get_slave_bufferlen':
src/core/spi_datalayer/spi_datalayer.c:130:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  return *(uint32_t*)&temp_spi_rx_buf[packet_delay + 7];
  ^
src/core/ssp0_slave/ssp0_slave.c: In function 'SSP0_IRQHandler':
src/core/ssp0_slave/ssp0_slave.c:81:5: warning: implicit declaration of function 'spi_DL_slave_state_machine' [-Wimplicit-function-declaration]
     LPC_SSP0->DR = spi_DL_slave_state_machine(LPC_SSP0->DR);
     ^
```

**Comment by microbuilder** [comment]
I'll have to clean up those warnings (the SPI slave code doesn't fully work and is highly experimental), but I did at least update the makefile so that it builds now.  Thanks for the reminder.
