### ISSUE TITLE
Bug in src/drivers/storage/fatfs/mmc.c when configuring CD and SSEL pin.

### ISSUE THREAD

**Issue by ve2yag** [microbuilder/LPC11U_LPC13U_CodeBase#16]
Line 327:
        LPC_GPIO->DIR[CFG_SDCARD_ENBLPORT] |= (1 << CFG_SDCARD_ENBLPORT);
        LPC_GPIO->DIR[CFG_SDCARD_SSELPORT] |= (1 << CFG_SDCARD_SSELPORT);

Must be replaced by:
        LPC_GPIO->DIR[CFG_SDCARD_ENBLPORT] |= (1 << CFG_SDCARD_ENBLPIN);
        LPC_GPIO->DIR[CFG_SDCARD_SSELPORT] |= (1 << CFG_SDCARD_SSELPIN);

Thank!

Remi

**Comment by microbuilder** [comment]
This is already fixed in the development branch, and will make it into the next major update, but thanks for the reminder to get the development code cleaned up and out there!
