### ISSUE TITLE
C++ typo in  src / core / usb / romdriver / mw_usbd_cdcuser.h

### ISSUE THREAD

**Issue by tommag** [microbuilder/LPC11U_LPC13U_CodeBase#21]
At the end of the mw_usbd_cdcuser.h,
# ifdef __cplusplus

extern "C" {
# endif

should be
# ifdef __cplusplus

}
# endif

I'm also trying to get the RTOS to work with a C++ application, for now I have linking errors but I'll keep you informed when I find the solution !

Thanks for the great work on this codebase.

Tom

**Comment by hathach** [comment]
fix at commit SHA: 8c83fc3c3ff633086f12f28fef1382de0b77387c in development branch
