### ISSUE TITLE
Internal eeprom access bug

### ISSUE THREAD

**Issue by ve2yag** [microbuilder/LPC11U_LPC13U_CodeBase#5]
I just debugged my own code and see you have the same problem in codebase.

On internal eeprom access, must disable interrupt on iap call because flash space are not avalaible when access to eeprom. Interrupt code and interrupt vector must be in RAM. I prefer to disable interrupt in my case.

Also the iap function use top 32 bytes of memory for internal operation. Stack pointer must be lowered by 32 bytes. Maximum stack usage on IAP call was 128 bytes from user program stack.

These little details cause me headache and CPU crash randomly on eeprom access.

-Interrupt during IAP, LPC1347 manual rev 4, section 21.8.7
-RAM used on IAP call, LPC1347 manual rev. 4 section 21.8.9

**Comment by microbuilder** [comment]
Thanks for the tip. I've fixed this locally to disable interrupts just before the IAP call, and placed the IAP functions in SRAM.  This will get pushed into the next update of the code base.
