### ISSUE TITLE
ADC configuration config suggestion...

### ISSUE THREAD

**Issue by ve2yag** [microbuilder/LPC11U_LPC13U_CodeBase#7]
For my project I modify adc.h to select 10-bit and uncomment line in adc.c for to configure pin usage.

I suggest to move #define in board configuration to choose which pin to configure as ADC pin and to choose bit mode. This change will prevent me to change adc.h/adc.c and keep codebase clean as possible...

Thank !! 

-Remi

**Comment by microbuilder** [comment]
Thanks for the feedback.  I moved the low power and 10-bit settings to the config file, but pin setup should normally be done in boardInit in my opinion.  The changes will make it into the next push.
