### ISSUE TITLE
LPC11U24/37 and LPC1347 ADC peripherals are not the same

### ISSUE THREAD

**Issue by opsound** [microbuilder/LPC11U_LPC13U_CodeBase#8]
The LPC_ADC->CR registers are different between the LPC1347 and the LPC11Uxx.

It looks like the current code is written for the LPC1347 ADC.  

LPWRMODE and MODE10BIT (22, 23) are only available on the LPC1347.  On the LPC11Uxx, they are reserved and ones shouldn't be written to them.

**Comment by opsound** [comment]
Related: 

the CLKS bits are only relevant to the LPC11Uxx and are reserved on the LPC1347

**Comment by microbuilder** [comment]
Thanks for the heads up.  I'll work this into the next update.

**Comment by opsound** [comment]
Also instead of this in adcRead()
regVal = *(volatile unsigned long *)(LPC_ADC_BASE + ADC_OFFSET + ADC_INDEX \* channelNum);

You should be able to write this
regVal = LPC_ADC->DR[channelNum];

as this is the same in LPC13Uxx.h and LPC11Uxx.h

**Comment by microbuilder** [comment]
Thanks again for the feedback.  I just made these changes locally and they'll make it into the next update, hopefully in a few days once I clean up a couple other issues.
